let list = `{
  "array": [
    {
      "cod": "4604049097555",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "url": "images/products/biomio.jpg",
      "sizeType": "масса",
      "size": 90,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом", "уход за руками"]
    },
    {
      "cod": "4604049097566",
      "name": "Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "url": "images/products/ariel.jpg",
      "sizeType": "масса",
      "size": "15X28.8",
      "manufacturer": "Нэфис",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097577",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "url": "images/products/sorti.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097588",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "url": "images/products/bimax.jpg",
      "sizeType": "масса",
      "size": 1500,
      "manufacturer": "Нэфис",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом"]
    },
    {
      "cod": "4604049097599",
      "name": "средство для мытья посуды Crystal",
      "url": "images/products/aos.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097555",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "url": "images/products/biomio.jpg",
      "sizeType": "масса",
      "size": 90,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом", "уход за руками"]
    },
    {
      "cod": "4604049097566",
      "name": "Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "url": "images/products/ariel.jpg",
      "sizeType": "масса",
      "size": "15X28.8",
      "manufacturer": "Нэфис",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097577",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "url": "images/products/sorti.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097588",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "url": "images/products/bimax.jpg",
      "sizeType": "масса",
      "size": 1500,
      "manufacturer": "Нэфис",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом"]
    },
    {
      "cod": "4604049097599",
      "name": "средство для мытья посуды Crystal",
      "url": "images/products/aos.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097555",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "url": "images/products/biomio.jpg",
      "sizeType": "масса",
      "size": 90,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом", "уход за руками"]
    },
    {
      "cod": "4604049097566",
      "name": "Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "url": "images/products/ariel.jpg",
      "sizeType": "масса",
      "size": "15X28.8",
      "manufacturer": "Нэфис",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097577",
      "name": "Ср-во для мытья посуды Апельсин+мята",
      "url": "images/products/sorti.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097588",
      "name": "Порошок стиральный Автомат 100 пятен COMPACT",
      "url": "images/products/bimax.jpg",
      "sizeType": "масса",
      "size": 1500,
      "manufacturer": "Нэфис",
      "brand": "BIMAX",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом"]
    },
    {
      "cod": "4604049097599",
      "name": "средство для мытья посуды Crystal",
      "url": "images/products/aos.jpg",
      "sizeType": "объем",
      "size": 450,
      "manufacturer": "Нэфис",
      "brand": "AOS",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    },
    {
      "cod": "4604049097555",
      "name": "BIO-SOAP Экологичное туалетное мыло. Литсея и бергамот",
      "url": "images/products/biomio.jpg",
      "sizeType": "масса",
      "size": 90,
      "manufacturer": "BioMio",
      "brand": "BioMio",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за телом", "уход за руками"]
    },
    {
      "cod": "4604049097566",
      "name": "Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
      "url": "images/products/ariel.jpg",
      "sizeType": "масса",
      "size": "15X28.8",
      "manufacturer": "Нэфис",
      "brand": "ARIEL",
      "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis.",
      "price": "48,76",
      "careType": ["уход за руками"]
    }
  ]
}`